### ISSUE TITLE
Show the existing SpiceDB instance's schema and relations when deploying the playground

### ISSUE THREAD

**Issue by lzbht** [authzed/playground#14]
1. create a spiceDB instance and fill the data (schema / relationships / permissons)
2. use playground to show the existed spiceDB data

**Comment by cbonami** [comment]
I guess you want to connect the playground to an 'external' (non-WASM) SpiceDb that is running already somewhere, and has data already provisioned to it?

**Comment by lzbht** [comment]
> I guess you want to connect the playground to an 'external' (non-WASM) SpiceDb that is running already somewhere, and has data already provisioned to it? Isn't this a duplicate of [authzed/spicedb#1075](https://github.com/authzed/spicedb/issues/1075) ?

You are right, my fault
