### ISSUE TITLE
Can't run Docker Image

### ISSUE THREAD

**Issue by jmkolbe** [authzed/playground#5]
Attempting to run the official Docker image (sha256:6d0bea9c40d8e5837a7c2e907045341d7be13be8101801661e03f558c7c3a878) as described in the [README ](https://github.com/authzed/playground#docker) fails with

```
docker run -it -p 3001:3000 ghcr.io/authzed/spicedb-playground:latest
WARNING: The requested image's platform (linux/arm64/v8) does not match the detected host platform (linux/amd64/v4) and no specific platform was requested
exec ./docker-entrypoint-wrapper.sh: exec format error
```

An image build from the main branch (ref 769c8ec) works, this might just be about publishing a new Docker image.

**Comment by arykalin** [comment]
Same problem

**Comment by samkim** [comment]
Just published a new image that targets amd64 so it should work for you. We'll add multi-arch builds to include arm in the future.
